default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: srvadmin_development

test:
  <<: *default
  database: srvadmin_test

production:
  <<: *default
  database: srvadmin_production
  username: srvadmin
  password: <%= ENV['SRVADMIN_DATABASE_PASSWORD'] %>
